# Generated by Django 4.1.3 on 2022-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=256)),
                ('bairro', models.CharField(max_length=256)),
                ('cidade', models.CharField(max_length=256)),
            ],
        ),
    ]
