# Generated by Django 4.1.3 on 2022-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='image',
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
